services:
  postgres:
    image: postgres:16
    container_name: healty_postgres
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    networks:
      - healty_network

  n8n:
    image: n8nio/n8n:latest
    container_name: healty_n8n
    restart: unless-stopped

    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_PORT: 5678


      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_HOST: ${N8N_HOST}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_BASE_URL}

      TZ: ${TZ}
      GENERIC_TIMEZONE: ${TZ}

    ports:
      - "${N8N_PORT}:5678"

    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./files:/home/node/.n8n-files
      - ./files:/files

    networks:
      - healty_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://n8n:5678
    depends_on:
      - n8n
    networks:
      - healty_network

networks:
  healty_network:
    driver: bridge
